<?php
// // 3.1.1 - txtDocRoot

// translated by František Bartoš (Bart, admin@bart.cz)

$langues = array(
	'langue' => 'Czech',
	'locale' => 'czech',
	'titreHtml' => 'WAMPSERVER Přehled',
	'titreConf' => 'Konfigurace serveru',
	'versa' => 'Apache verze:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/en/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/en/',
	'versp' => 'PHP verze:',
	'server' => 'Software serveru:',
	'documentation' => 'Dokumentace',
	'docp' => 'www.php.net/manual/en/',
	'versm' => 'MySQL verze:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'MariaDB verze: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Načtená rozšíření: ',
	'titrePage' => 'Nástroje',
	'txtProjet' => 'Projekty',
	'txtNoProjet' => 'Zatím žádný projekt.<br />Chcete-li vytvořit nový PROJEKT, stačí vytvořit nový adresář s projektem v adresáři \'www\'.',
	'txtAlias' => 'Aliasy',
	'txtNoAlias' => 'Zatím žádný Alias.<br />Chcete-li vytvořit nový ALIAS, použijte nabídku v menu WAMPSERVER.',
	'txtVhost' => 'VirtualHost',
	'txtServerName' => 'ServerName %s má chybnou syntaxi v souboru %s',
	'txtDocRoot' => 'ServerName %s používá DocumentRoot %s vyhrazený pro localhost',
	'txtServerNameIp' => 'IP adresa %s pro Servername %s v souboru %s není platná',
	'txtVhostNotClean' => 'Soubor %s nebyl vyčištěn. Zde je příklad pro VirtualHost: dummy-host.example.com',
	'txtNoVhost' => 'Zatím žádný VirtualHost. Přidejte pro záznam pro každý projekt zvlášt v souboru: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Odkomentujte nebo přidejte <i>Include conf/extra/httpd-vhosts.conf</i> v souboru wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Soubor: %s neexistuje',
	'txtNoPath' => 'Cesta %s k %s neexistuje (Soubor %s)',
	'txtNotWritable' => 'Soubor: %s není zapisovatelný',
	'txtNbNotEqual' => 'Počet %s neodpovídá počtu %s v souboru %s',
	'txtAddVhost' => 'Přidat Virtual Host',
	'txtPortNumber' => 'Číslo portu pro %s nemá správnou hodnotu nebo není stejné v souboru %s',
	'txtCorrected' => 'Některé chyby ve VirtualHosts lze opravit.',
	'forum' => 'Wampserver Fórum',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Definovaný port pro Apache: ',
	'mysqlportUsed' => 'Definovaný port pro MySQL: ',
	'mariaportUsed' => 'Definovaný port pro MariaDB: ',
	'nolocalhost' => 'Je to špatný nápad přidat localhost do URL adresy projektů při jejich zahájení. Nejlepší způsob je definovat VirtualHost v souboru<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br /> a do URL adresy tak localhost nepřidávat.',
	);
?>